name: Build
on:
  push:
    branches: [main, dev]
    paths-ignore:
      - "**/*.md"
      - ".github/**"

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          repository: "revenge-mod/builds"
          path: "builds"
          token: ${{ secrets.BUILDS_PUSH_TOKEN }}
          ref: ${{ github.ref_name }}

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: main
        run: bun i

      - name: CI
        working-directory: main
        run: bun run format

      - name: Build
        run: bun run build-bun

      - name: Push builds
        run: |
          rm $GITHUB_WORKSPACE/builds/* || true
          cp -r dist/* $GITHUB_WORKSPACE/builds || true
          cd $GITHUB_WORKSPACE/builds
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push

      # NOTE: Temporarily disabled, enable if needed
      - name: Purge CDN cache
        if: ${{ false }}
        run: |
          curl https://purge.jsdelivr.net/gh/revenge-mod/builds
