name: Build (debug)
on:
  push:
    branches-ignore: [main, dev]
    paths-ignore:
      - "**/*.md"
      - ".github/**"
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - "**/*.md"
      - ".github/**"
  workflow_dispatch:

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun i

      - name: CI
        run: bun run format

      - name: Build
        run: bun run build-bun

      - uses: actions/upload-artifact@v4
        with:
          name: revenge-build-debug
          path: dist/*.js
          if-no-files-found: error
